theme: jekyll-theme-primer

title: Apprentissage artificiel
description: Contenus pour le cours Â«â€¯Apprentissage automatiqueâ€¯Â» du master Plurital.
emojicon: ðŸ¤–

url: https://loicgrobol.github.io/
baseurl: /apprentissage-artificiel
repository: "loicgrobol/apprendre-programmer"
repo_branch: "main"

exclude:
  - "*.py.md"
  - "**/local"

include:
  - _pages
  - "*.py.html"
  - "pdf_slides/*"
